name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: ./build/bin/tdc -v
      - run: ./build/bin/tdc -h
      - run: ./build/bin/tdc
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install cpplint===1.6.1
      - run: sudo snap install cppcheck
      - run: make lint
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make dist
